In [1]:
s = 0
for i in range(1000):
  s += 0.001

print(s)

1.0000000000000007


In [ ]:
# s = 0
# while s = != 1.:
#   print(s)
#   s += 0.1

In [1]:
eps = 1e-10
s = 0
while abs(s - 1.) > eps:
  print(s)
  s += 0.1

0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999


In [2]:
import numpy as np
np.exp(1000)

/var/folders/yb/0fg_8nv17y5fjj0s_tq9clbh0000gn/T/ipykernel_7678/2816224678.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(1000)


inf

In [3]:
np.exp(2)

7.38905609893065

In [7]:
np.log(np.e)

1.0

In [8]:
np.sin(np.pi)

1.2246467991473532e-16

In [9]:
np.sqrt(3)

1.7320508075688772

In [11]:
a = np.array([2,3,5,7,8])
a[0]

2

In [12]:
a[1:3]

array([3, 5])

In [13]:
a[2:-2]

array([5])

In [15]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [17]:
c = np.arange(1, 3, 0.2)
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [18]:
a.dtype

dtype('int64')

In [19]:
c.dtype

dtype('float64')

In [20]:
d = np.array([1, 2, 3], dtype=np.float64)
d

array([1., 2., 3.])

In [21]:
d.dtype

dtype('float64')

In [22]:
e = np.arange(5.)
e

array([0., 1., 2., 3., 4.])

In [24]:
e.dtype

dtype('float64')

In [26]:
a = np.array([[2,3,4],[5,6,7]], dtype=np.float64)
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [27]:
a[0,1]

3.0

In [28]:
a[:,1]

array([3., 6.])

In [29]:
a[1,:]

array([5., 6., 7.])

In [30]:
a[0, 2:]

array([4.])

In [32]:
a[0, :2]

array([2., 3.])

In [34]:
a = np.arange(15.).reshape(3,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [35]:
a.shape

(3, 5)

In [36]:
a.ndim

2

In [37]:
a.size

15

In [38]:
b = np.arange(4.)
b.shape

(4,)

In [39]:
b.ndim

1

In [40]:
b.size

4

In [41]:
a = np.arange(16.)
c = a.reshape(4, -1)
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [42]:
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])